"use client";

import { AircraftInterface } from "@/components/Card";

export const airports = [
  {
    value: "CGK",
    label: "Soekarno-Hatta International Airport",
    latitude: -6.1256,
    longitude: 106.6559,
  },
  {
    value: "DPS",
    label: "Ngurah Rai International Airport",
    latitude: -8.7443704,
    longitude: 115.1562271,
  },
  {
    value: "LPG",
    label: "Raden Intan II",
    latitude: -5.2452552,
    longitude: 105.1782849,
  },
];

export const tabs = [
  {
    icon: "/assets/svg/single-flight.svg",
    label: "Single Flight",
    labelMobile: "Single",
    height: 20,
    widht: 20,
  },
  {
    icon: "/assets/svg/round-flight.svg",
    label: "Round Flight",
    labelMobile: "Round",
    height: 30,
    widht: 30,
  },
  {
    icon: "/assets/svg/multiple-destination.svg",
    label: "Multiple Destinations",
    labelMobile: "Multiple",
    height: 30,
    widht: 30,
  },
];

export const dataPrivateJet: AircraftInterface[] = [
  {
    id: "gulfstream-g650",
    brand: "Gulfstream",
    model: "G650",
    name: "Gulfstream G650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Halim Perdana Kusuma",
    passenger_capacity: 6,
    price: 75000,
  },
  {
    id: "cessna-citation-x",
    brand: "Cessna",
    model: "Citation X",
    name: "Cessna Citation X",
    image: "/assets/images/image-aircraft.webp",
    airport: "Soekarno-Hatta International",
    passenger_capacity: 4,
    price: 55000,
  },
  {
    id: "bombardier-global-6000",
    brand: "Bombardier",
    model: "Global 6000",
    name: "Bombardier Global 6000",
    image: "/assets/images/image-aircraft.webp",
    airport: "Ngurah Rai International",
    passenger_capacity: 8,
    price: 92000,
  },
  {
    id: "embraer-legacy-650",
    brand: "Embraer",
    model: "Legacy 650",
    name: "Embraer Legacy 650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Juanda International",
    passenger_capacity: 5,
    price: 68000,
  },
  {
    id: "gulfstream-g650",
    brand: "Gulfstream",
    model: "G650",
    name: "Gulfstream G650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Halim Perdana Kusuma",
    passenger_capacity: 6,
    price: 75000,
  },
  {
    id: "cessna-citation-x",
    brand: "Cessna",
    model: "Citation X",
    name: "Cessna Citation X",
    image: "/assets/images/image-aircraft.webp",
    airport: "Soekarno-Hatta International",
    passenger_capacity: 4,
    price: 55000,
  },
  {
    id: "bombardier-global-6000",
    brand: "Bombardier",
    model: "Global 6000",
    name: "Bombardier Global 6000",
    image: "/assets/images/image-aircraft.webp",
    airport: "Ngurah Rai International",
    passenger_capacity: 8,
    price: 92000,
  },
  {
    id: "embraer-legacy-650",
    brand: "Embraer",
    model: "Legacy 650",
    name: "Embraer Legacy 650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Juanda International",
    passenger_capacity: 5,
    price: 68000,
  },
  {
    id: "gulfstream-g650",
    brand: "Gulfstream",
    model: "G650",
    name: "Gulfstream G650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Halim Perdana Kusuma",
    passenger_capacity: 6,
    price: 75000,
  },
  {
    id: "cessna-citation-x",
    brand: "Cessna",
    model: "Citation X",
    name: "Cessna Citation X",
    image: "/assets/images/image-aircraft.webp",
    airport: "Soekarno-Hatta International",
    passenger_capacity: 4,
    price: 55000,
  },
  {
    id: "bombardier-global-6000",
    brand: "Bombardier",
    model: "Global 6000",
    name: "Bombardier Global 6000",
    image: "/assets/images/image-aircraft.webp",
    airport: "Ngurah Rai International",
    passenger_capacity: 8,
    price: 92000,
  },
  {
    id: "embraer-legacy-650",
    brand: "Embraer",
    model: "Legacy 650",
    name: "Embraer Legacy 650",
    image: "/assets/images/image-aircraft.webp",
    airport: "Juanda International",
    passenger_capacity: 5,
    price: 68000,
  },
];

export const images = [
  "/assets/images/image-aircraft.webp",
  "/assets/images/image-aircraft.webp",
  "/assets/images/image-aircraft.webp",
  "/assets/images/image-aircraft.webp",
  "/assets/images/image-aircraft.webp",
];
